baseURL       = "https://coumba-khonte.netlify.app"
languageCode  = "fr-FR"
title         = "Roxo | NWS portfolio starter theme"
theme         = "roxo"
summarylength = 25

# Site Menus
[menu]
  # Navbar Menus
  [[menu.nav]]
    name    = "ACCEUIL"
    url     = ""
    weight  = 1
  [[menu.nav]]
    name    = "QUI SUIS JE"
    url     = "about"
    weight  = 2
  [[menu.nav]]
    name    = "PORTFOLIO"
    url     = "portfolio"
    weight  = 3
  [[menu.nav]]
    name    = "BLOG"
    url     = "blog"
    weight  = 4
  [[menu.nav]]
    name    = "Contact"
    url     = "contact"
    weight  = 5

# Site Params
[params]
  logo = "images/logo.png"
  dateFormat = "26 FEB 1994"
  # Meta data
  description = "Roxo Hugo themes | Design Agency Template by StaticMania"
  author = "StaticMania"
  # Google Analitycs
  googleAnalitycsID = "Your ID"
  # We're using formspree.io for form handling, paste your formspree url below
  formspreeFormUrl  = "https://formspree.io/myykjpje"
  
  # Navbar Action Button
  [params.navAction]
    status  = true
    name    = "Get in touch"
    url     = "contact"
  

  # Banner Section
  [params.banner]
    enable                = true
    background_image      = "images/backgrounds/hero-background.png .jpg"
    heading               = "Collaborons ensemble !"
    tagline               = ""
    primary_button        = ""
    primary_button_url    = ""
    secondary_button      = "Accés Travaux"
    secondary_button_url  = "contact"

  [params.portfolio]
    enable    = true
    title     = "TRAVAUX "
    subtitle  = ""

  [params.call_to_action]
    enable              = true
    background_image    = "images/backgrounds/hero-background.png"
    title               = "LET'S WORK TOGETHER"
    primary_button      = "Submit Query"
    primary_button_url  = "contact"
    secondary_button    = "Not Convinced"
    secondary_button_url = "portfolio"

  [params.footer]
    # Footer Contact Info
    [params.footer.contactInfo]
      title   = "Contact"
      address = "26 rue Saint-Rémy"
      phone   = "+33 6 95 09 81 61 "
      email   = "c.khontepro@gmail.com"
      # Footer Sitemap
      [params.footer.sitemap]
        title   = "Plan du site"
        [[params.footer.sitemap.link]]
          name = "A propos"
          url  = "A propos "
        [[params.footer.sitemap.link]]
          name = "Portfolio"
          url  = "portfolio"
        [[params.footer.sitemap.link]]
          name = "Blog"
          url  = "blog"
        [[params.footer.sitemap.link]]
          name = "Contact"
          url  = "contact"
      # Footer Social Media
      [params.footer.social]
        title   = "Réseaux sociaux"
        [[params.footer.social.link]]
          name = ""
          url  = "#"
        [[params.footer.social.link]]
          name = "Facebook"
          url  = "https://www.facebook.com/coumbiss.llagalsen/"
        [[params.footer.social.link]]
          name = "Linkedin"
          url  = "https://www.linkedin.com/in/coumba-khonté-b4b6061bb/"
        [[params.footer.social.link]]
          name = "Instagram"
          url  = "https://www.instagram.com/coumba_kht/"
      # Footer Service
      [params.footer.service]
        title       = ""
        description = ""